[package]
name = "rustentia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.0"
env_logger = "0.10"
rusqlite = { version = "0.29.0", features = ["bundled"] }
egui-notify = "0.6.0"
